# Generated by Django 4.0.1 on 2022-02-08 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_projects_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.ImageField(blank=True, default='photos/website.jpg', null=True, upload_to='photos/'),
        ),
    ]
