# Generated by Django 4.0.1 on 2022-02-08 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_projects_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='projects',
            new_name='Project',
        ),
    ]
