# Generated by Django 4.0.1 on 2022-02-08 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_rename_projects_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, default='photos/web.jpg', null=True, upload_to='photos/'),
        ),
    ]
