# Generated by Django 4.0.1 on 2022-03-03 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_message'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
